### ISSUE TITLE
staging workflow: 'osc staging check LETER' no longer possible

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/obs_factory#77]
Since the recent deployments, it is no longer possible to call

```osc staging check A```

This tries to query
/project/staging_projects/openSUSE:Factory/A?format=json

which in turn returns an 'error 500'

**Comment by DimStar77** [comment]
@jberry-suse CC

**Comment by lnussel** [comment]
caused by https://github.com/openSUSE/obs_factory/commit/c40b932f3d787140ca426cd4a6cea7589202b0c8

**Comment by DimStar77** [comment]
From the OBS Team we got this reference from the log files:

```
NameError: undefined local variable or method `staging_project' for #<ObsFactory::StagingProjectsController:0x007fe66fdcd130> Did you mean? @staging_project staging_project_url
```

**Comment by jberry-suse** [comment]
Someone with permission: this issue can be closed. @coolo
